/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CropsIndexRouteImport } from './routes/crops.index'
import { Route as CropsNewRouteImport } from './routes/crops.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsIndexRoute = CropsIndexRouteImport.update({
  id: '/crops/',
  path: '/crops/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsNewRoute = CropsNewRouteImport.update({
  id: '/crops/new',
  path: '/crops/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crops/new': typeof CropsNewRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crops/new': typeof CropsNewRoute
  '/crops': typeof CropsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crops/new': typeof CropsNewRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crops/new' | '/crops/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crops/new' | '/crops'
  id: '__root__' | '/' | '/crops/new' | '/crops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropsNewRoute: typeof CropsNewRoute
  CropsIndexRoute: typeof CropsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/': {
      id: '/crops/'
      path: '/crops'
      fullPath: '/crops/'
      preLoaderRoute: typeof CropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/new': {
      id: '/crops/new'
      path: '/crops/new'
      fullPath: '/crops/new'
      preLoaderRoute: typeof CropsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropsNewRoute: CropsNewRoute,
  CropsIndexRoute: CropsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
