/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as PassportsRouteImport } from './routes/passports'
import { Route as CropsIndexRouteImport } from './routes/crops.index'
import { Route as CropsCropIdRouteImport } from './routes/crops.$cropId'
import { Route as CropsNewRouteImport } from './routes/crops.new'
import { Route as PassportCropIdRouteImport } from './routes/passport.$cropId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportsRoute = PassportsRouteImport.update({
  id: '/passports',
  path: '/passports',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsIndexRoute = CropsIndexRouteImport.update({
  id: '/crops/',
  path: '/crops/',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsCropIdRoute = CropsCropIdRouteImport.update({
  id: '/crops/$cropId',
  path: '/crops/$cropId',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsNewRoute = CropsNewRouteImport.update({
  id: '/crops/new',
  path: '/crops/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportCropIdRoute = PassportCropIdRouteImport.update({
  id: '/passport/$cropId',
  path: '/passport/$cropId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/passports': typeof PassportsRoute
  '/crops/$cropId': typeof CropsCropIdRoute
  '/crops/new': typeof CropsNewRoute
  '/passport/$cropId': typeof PassportCropIdRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/passports': typeof PassportsRoute
  '/crops/$cropId': typeof CropsCropIdRoute
  '/crops/new': typeof CropsNewRoute
  '/passport/$cropId': typeof PassportCropIdRoute
  '/crops': typeof CropsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/passports': typeof PassportsRoute
  '/crops/$cropId': typeof CropsCropIdRoute
  '/crops/new': typeof CropsNewRoute
  '/passport/$cropId': typeof PassportCropIdRoute
  '/crops/': typeof CropsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/passports'
    | '/crops/$cropId'
    | '/crops/new'
    | '/passport/$cropId'
    | '/crops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/passports'
    | '/crops/$cropId'
    | '/crops/new'
    | '/passport/$cropId'
    | '/crops'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/passports'
    | '/crops/$cropId'
    | '/crops/new'
    | '/passport/$cropId'
    | '/crops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  PassportsRoute: typeof PassportsRoute
  CropsCropIdRoute: typeof CropsCropIdRoute
  CropsNewRoute: typeof CropsNewRoute
  PassportCropIdRoute: typeof PassportCropIdRoute
  CropsIndexRoute: typeof CropsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passports': {
      id: '/passports'
      path: '/passports'
      fullPath: '/passports'
      preLoaderRoute: typeof PassportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/': {
      id: '/crops/'
      path: '/crops'
      fullPath: '/crops/'
      preLoaderRoute: typeof CropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$cropId': {
      id: '/crops/$cropId'
      path: '/crops/$cropId'
      fullPath: '/crops/$cropId'
      preLoaderRoute: typeof CropsCropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/new': {
      id: '/crops/new'
      path: '/crops/new'
      fullPath: '/crops/new'
      preLoaderRoute: typeof CropsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$cropId': {
      id: '/passport/$cropId'
      path: '/passport/$cropId'
      fullPath: '/passport/$cropId'
      preLoaderRoute: typeof PassportCropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  PassportsRoute: PassportsRoute,
  CropsCropIdRoute: CropsCropIdRoute,
  CropsNewRoute: CropsNewRoute,
  PassportCropIdRoute: PassportCropIdRoute,
  CropsIndexRoute: CropsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
